# Generated by Django 4.2.7 on 2023-11-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flow', '0007_alter_event_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Roadmap',
            field=models.TextField(default='', null=True),
        ),
    ]
