# Generated by Django 4.2.7 on 2023-11-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flow', '0007_alter_tags_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default='', max_length=100),
        ),
    ]
