# Generated by Django 4.2.7 on 2023-11-21 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Flow', '0008_alter_event_roadmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='is_paid_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='money_man',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_man', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tags',
            name='events',
            field=models.ManyToManyField(related_name='tags', to='Flow.event'),
        ),
        migrations.AddField(
            model_name='tags',
            name='nb_events',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
