# Generated by Django 4.2.7 on 2023-11-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flow', '0009_remove_tags_event_event_is_paid_event_and_more'),
        ('Flow', '0009_remove_tags_event_tags_event'),
    ]

    operations = [
    ]
