# Generated by Django 4.2.7 on 2023-11-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flow', '0009_remove_tags_event_tags_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='tags',
            name='event',
            field=models.ManyToManyField(related_name='tags', to='Flow.event'),
        ),
    ]
