# Generated by Django 4.2.7 on 2023-11-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flow', '0010_merge_20231121_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='event',
            field=models.ManyToManyField(related_name='tag', to='Flow.event'),
        ),
    ]
