# Generated by Django 4.2.7 on 2023-11-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flow', '0010_rename_tag_tags_tags_alter_tags_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('conference', 'Conférence'), ('workshop', 'Atelier'), ('meetup', 'Rencontre'), ('party', 'Soirée'), ('spectacle', 'Spectacle'), ('sport', 'Sport'), ('other', 'Autre')], default='other', max_length=20),
        ),
    ]
