# Generated by Django 4.2.7 on 2023-11-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flow', '0011_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='event',
            field=models.ManyToManyField(blank=True, related_name='tags', to='Flow.event'),
        ),
    ]
