# Generated by Django 4.2.7 on 2023-11-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flow', '0013_alter_event_likes_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='event',
            new_name='event_id',
        ),
    ]
