# Generated by Django 4.2.7 on 2023-11-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flow', '0014_alter_tags_event'),
        ('Flow', '0015_alter_like_event_id'),
    ]

    operations = [
    ]
