# Generated by Django 4.2.7 on 2023-11-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flow', '0016_merge_0014_alter_tags_event_0015_alter_like_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='events',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='nb_events',
        ),
    ]
