# Generated by Django 4.2.7 on 2023-11-18 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_room_created_by_room_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='created_by',
        ),
    ]
