# Generated by Django 4.2.7 on 2023-11-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_remove_room_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='uuid',
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
