# Generated by Django 4.2.7 on 2023-11-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_remove_room_uuid_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='eId',
            field=models.IntegerField(default=0),
        ),
    ]
