# Generated by Django 4.2.7 on 2023-11-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_remove_room_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('closed', 'closed'), ('active', 'active')], default='active', max_length=20),
        ),
    ]
