# Generated by Django 4.2.7 on 2023-11-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_utilisateur_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
