# Generated by Django 4.2.7 on 2023-11-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_alter_utilisateur_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='CA',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='created_nb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='joined_nb',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
