# Generated by Django 4.2.7 on 2023-11-21 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Authentication', '0005_utilisateur_ca_utilisateur_created_nb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='CA',
            new_name='CA_buys',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='CA_sales',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_validated_money_man',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur', to=settings.AUTH_USER_MODEL),
        ),
    ]
