# Generated by Django 4.2.7 on 2023-11-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_rename_ca_utilisateur_ca_buys_utilisateur_ca_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.jpg', null=True, upload_to='avatar/'),
        ),
    ]
