# Generated by Django 4.2.7 on 2023-11-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_utilisateur_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='money_man_request_pending',
            field=models.BooleanField(default=False),
        ),
    ]
